[package]
name = "planned"
version = "0.1.0"
authors = ["Arijit Dey <arijid79@gmail.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
